// Enhanced photo interface with metadata
export interface PhotoMetadata {
  id: string
  src: string
  alt: string
  title?: string
  description?: string
  date?: string
  location?: string
  tags?: string[]
  featured?: boolean
  order?: number
  uploadedAt: string
  fileSize?: number
  dimensions?: {
    width: number
    height: number
  }
}

export interface GalleryCategory {
  id: string
  title: string
  description: string
  heroImage: string
  photos: PhotoMetadata[]
  totalPhotos: number
}

// ---------------------------------------------------------------------------
// Gallery photos mapped to real files in /public
// Featured gallery images are in /public/gallery/featured/
// Note: filenames contain spaces — Next.js Image handles these correctly.
// ---------------------------------------------------------------------------

const featuredPhotos: PhotoMetadata[] = [
  {
    id: "f1",
    src: "/gallery/featured/hero (1).jpg",
    alt: "Wedding photography session",
    title: "Wedding Moments",
    date: "2024-06-15",
    location: "South Jersey",
    tags: ["wedding", "portrait"],
    featured: true,
    order: 1,
    uploadedAt: "2024-06-15T10:00:00Z",
  },
  {
    id: "f3",
    src: "/gallery/featured/hero (3).jpg",
    alt: "Wedding photography session",
    title: "Bridal Details",
    date: "2024-06-15",
    location: "South Jersey",
    tags: ["wedding", "details"],
    featured: true,
    order: 2,
    uploadedAt: "2024-06-15T10:05:00Z",
  },
  {
    id: "f5",
    src: "/gallery/featured/hero (5).jpg",
    alt: "Wedding photography",
    title: "Ceremony",
    date: "2024-07-20",
    location: "Philadelphia, PA",
    tags: ["wedding", "ceremony"],
    featured: false,
    order: 3,
    uploadedAt: "2024-07-20T14:00:00Z",
  },
  {
    id: "f6",
    src: "/gallery/featured/hero (6).jpg",
    alt: "Wedding photography",
    title: "Reception Joy",
    date: "2024-07-20",
    location: "Philadelphia, PA",
    tags: ["wedding", "reception"],
    featured: false,
    order: 4,
    uploadedAt: "2024-07-20T14:05:00Z",
  },
  {
    id: "f8",
    src: "/gallery/featured/hero (8).jpg",
    alt: "Wedding photography session",
    title: "First Look",
    date: "2024-08-10",
    location: "Cherry Hill, NJ",
    tags: ["wedding", "first-look"],
    featured: false,
    order: 5,
    uploadedAt: "2024-08-10T10:00:00Z",
  },
  {
    id: "f9",
    src: "/gallery/featured/hero (9).jpg",
    alt: "Wedding photography session",
    title: "Wedding Portrait",
    date: "2024-08-10",
    location: "Cherry Hill, NJ",
    tags: ["wedding", "portrait"],
    featured: false,
    order: 6,
    uploadedAt: "2024-08-10T10:05:00Z",
  },
  {
    id: "f10",
    src: "/gallery/featured/hero (10).jpg",
    alt: "Wedding photography",
    title: "Golden Hour",
    date: "2024-09-05",
    location: "South Jersey",
    tags: ["wedding", "golden-hour"],
    featured: true,
    order: 7,
    uploadedAt: "2024-09-05T17:00:00Z",
  },
  {
    id: "f11",
    src: "/gallery/featured/hero (11).jpg",
    alt: "Wedding photography",
    title: "The Kiss",
    date: "2024-09-05",
    location: "South Jersey",
    tags: ["wedding", "ceremony"],
    featured: false,
    order: 8,
    uploadedAt: "2024-09-05T17:05:00Z",
  },
  {
    id: "f12",
    src: "/gallery/featured/hero (12).jpg",
    alt: "Wedding photography",
    title: "Wedding Party",
    date: "2024-09-12",
    location: "Haddonfield, NJ",
    tags: ["wedding", "group"],
    featured: false,
    order: 9,
    uploadedAt: "2024-09-12T12:00:00Z",
  },
  {
    id: "f13",
    src: "/gallery/featured/hero (13).jpg",
    alt: "Wedding photography",
    title: "Elegant Reception",
    date: "2024-09-12",
    location: "Haddonfield, NJ",
    tags: ["wedding", "reception"],
    featured: false,
    order: 10,
    uploadedAt: "2024-09-12T19:00:00Z",
  },
  {
    id: "f14",
    src: "/gallery/featured/hero (14).jpg",
    alt: "Wedding photography",
    title: "Bridal Elegance",
    date: "2024-10-01",
    location: "Mount Laurel, NJ",
    tags: ["wedding", "bride"],
    featured: false,
    order: 11,
    uploadedAt: "2024-10-01T10:00:00Z",
  },
  {
    id: "f15",
    src: "/gallery/featured/hero (15).jpg",
    alt: "Wedding photography",
    title: "Vows",
    date: "2024-10-01",
    location: "Mount Laurel, NJ",
    tags: ["wedding", "ceremony", "vows"],
    featured: false,
    order: 12,
    uploadedAt: "2024-10-01T14:00:00Z",
  },
  {
    id: "f16",
    src: "/gallery/featured/hero (16).jpg",
    alt: "Wedding photography",
    title: "Outdoor Ceremony",
    date: "2024-10-15",
    location: "Medford, NJ",
    tags: ["wedding", "outdoor"],
    featured: false,
    order: 13,
    uploadedAt: "2024-10-15T15:00:00Z",
  },
  {
    id: "f18",
    src: "/gallery/featured/hero (18).jpg",
    alt: "Wedding photography",
    title: "Dancing Couple",
    date: "2024-10-15",
    location: "Medford, NJ",
    tags: ["wedding", "dance"],
    featured: true,
    order: 14,
    uploadedAt: "2024-10-15T20:00:00Z",
  },
  {
    id: "f20",
    src: "/gallery/featured/hero (20).jpg",
    alt: "Wedding photography",
    title: "Sunset Portrait",
    date: "2024-11-02",
    location: "South Jersey",
    tags: ["wedding", "sunset", "portrait"],
    featured: true,
    order: 15,
    uploadedAt: "2024-11-02T17:00:00Z",
  },
  {
    id: "f21",
    src: "/gallery/featured/hero (21).jpg",
    alt: "Wedding photography",
    title: "Candid Laughter",
    date: "2024-11-02",
    location: "South Jersey",
    tags: ["wedding", "candid"],
    featured: false,
    order: 16,
    uploadedAt: "2024-11-02T15:00:00Z",
  },
  {
    id: "f22",
    src: "/gallery/featured/hero (22).jpg",
    alt: "Wedding photography",
    title: "Romantic Walk",
    date: "2024-11-15",
    location: "Burlington, NJ",
    tags: ["wedding", "romantic"],
    featured: false,
    order: 17,
    uploadedAt: "2024-11-15T16:00:00Z",
  },
  {
    id: "f23",
    src: "/gallery/featured/hero (23).jpg",
    alt: "Wedding photography",
    title: "Floral Details",
    date: "2024-11-15",
    location: "Burlington, NJ",
    tags: ["wedding", "details", "flowers"],
    featured: false,
    order: 18,
    uploadedAt: "2024-11-15T12:00:00Z",
  },
  {
    id: "f24",
    src: "/gallery/featured/hero (24).jpg",
    alt: "Wedding photography",
    title: "Timeless Moment",
    date: "2024-12-01",
    location: "Voorhees, NJ",
    tags: ["wedding", "portrait"],
    featured: true,
    order: 19,
    uploadedAt: "2024-12-01T14:00:00Z",
  },
]

// This will be replaced by CMS data in production
export const galleryData: Record<string, GalleryCategory> = {
  weddings: {
    id: "weddings",
    title: "Weddings",
    description:
      "Capturing the magic of your special day with timeless elegance and authentic emotion.",
    heroImage: "/gallery/featured/hero (1).jpg",
    totalPhotos: featuredPhotos.length,
    photos: featuredPhotos,
  },

  engagement: {
    id: "engagement",
    title: "Engagement",
    description:
      "Celebrating your love story with romantic and playful engagement photography.",
    heroImage: "/romantic-engagement-couple.jpg",
    totalPhotos: 5,
    photos: [
      {
        id: "e1",
        src: "/romantic-engagement-couple.jpg",
        alt: "Romantic engagement couple",
        title: "Romantic Moment",
        description: "A tender moment between the engaged couple",
        date: "2024-05-20",
        location: "Princeton, NJ",
        tags: ["couple", "romantic", "engagement"],
        featured: true,
        order: 1,
        uploadedAt: "2024-05-20T14:00:00Z",
        dimensions: { width: 1200, height: 800 },
      },
      {
        id: "e2",
        src: "/gallery/hero (2).jpg",
        alt: "Engagement session",
        title: "Love Story",
        date: "2024-05-20",
        location: "Princeton, NJ",
        tags: ["couple", "engagement"],
        featured: false,
        order: 2,
        uploadedAt: "2024-05-20T14:10:00Z",
      },
      {
        id: "e3",
        src: "/gallery/hero (4).jpg",
        alt: "Engagement photography",
        title: "Together",
        date: "2024-06-10",
        location: "Cape May, NJ",
        tags: ["couple", "outdoor"],
        featured: false,
        order: 3,
        uploadedAt: "2024-06-10T11:00:00Z",
      },
      {
        id: "e4",
        src: "/home/couple-laughing.png",
        alt: "Couple laughing together",
        title: "Joyful Moments",
        date: "2024-06-10",
        location: "Cape May, NJ",
        tags: ["couple", "candid", "laughter"],
        featured: true,
        order: 4,
        uploadedAt: "2024-06-10T11:30:00Z",
      },
      {
        id: "e5",
        src: "/gallery/hero (25).jpg",
        alt: "Engagement photography",
        title: "Golden Afternoon",
        date: "2024-07-05",
        location: "Longwood Gardens, PA",
        tags: ["couple", "golden-hour"],
        featured: false,
        order: 5,
        uploadedAt: "2024-07-05T17:00:00Z",
      },
    ],
  },

  maternity: {
    id: "maternity",
    title: "Maternity",
    description:
      "Documenting the beautiful journey of motherhood with grace and artistry.",
    heroImage: "/beautiful-maternity-photo.png",
    totalPhotos: 4,
    photos: [
      {
        id: "m1",
        src: "/beautiful-maternity-photo.png",
        alt: "Beautiful maternity photo",
        title: "Expecting Mother",
        description: "Beautiful maternity portrait celebrating motherhood",
        date: "2024-04-10",
        location: "Camden, NJ",
        tags: ["maternity", "portrait", "motherhood"],
        featured: true,
        order: 1,
        uploadedAt: "2024-04-10T16:00:00Z",
        dimensions: { width: 800, height: 1200 },
      },
      {
        id: "m2",
        src: "/expecting-mother-silhouette.png",
        alt: "Expecting mother silhouette",
        title: "Silhouette",
        description: "An artistic silhouette celebrating the beauty of pregnancy",
        date: "2024-04-10",
        location: "Camden, NJ",
        tags: ["maternity", "silhouette", "artistic"],
        featured: true,
        order: 2,
        uploadedAt: "2024-04-10T16:30:00Z",
      },
      {
        id: "m3",
        src: "/gallery/hero (19).jpg",
        alt: "Maternity photography session",
        title: "Radiant",
        date: "2024-05-05",
        location: "Voorhees, NJ",
        tags: ["maternity", "portrait"],
        featured: false,
        order: 3,
        uploadedAt: "2024-05-05T10:00:00Z",
      },
      {
        id: "m4",
        src: "/gallery/hero (26).jpg",
        alt: "Maternity photography",
        title: "Growing Love",
        date: "2024-05-05",
        location: "Voorhees, NJ",
        tags: ["maternity", "outdoor"],
        featured: false,
        order: 4,
        uploadedAt: "2024-05-05T10:30:00Z",
      },
    ],
  },

  minis: {
    id: "minis",
    title: "Mini Sessions",
    description:
      "Quick and beautiful photography sessions perfect for families and couples.",
    heroImage: "/home/couple-laughing.png",
    totalPhotos: 3,
    photos: [
      {
        id: "mini1",
        src: "/home/couple-laughing.png",
        alt: "Mini session couple laughing",
        title: "Joyful Mini Session",
        date: "2024-09-28",
        location: "South Jersey",
        tags: ["mini-session", "couple", "candid"],
        featured: true,
        order: 1,
        uploadedAt: "2024-09-28T11:00:00Z",
      },
      {
        id: "mini2",
        src: "/gallery/3456.jpg",
        alt: "Mini photography session",
        title: "Quick & Beautiful",
        date: "2024-10-05",
        location: "Haddon Township, NJ",
        tags: ["mini-session"],
        featured: false,
        order: 2,
        uploadedAt: "2024-10-05T10:00:00Z",
      },
      {
        id: "mini3",
        src: "/gallery/123.png",
        alt: "Mini photography session",
        title: "Autumn Minis",
        date: "2024-10-05",
        location: "Haddon Township, NJ",
        tags: ["mini-session", "autumn"],
        featured: false,
        order: 3,
        uploadedAt: "2024-10-05T10:30:00Z",
      },
    ],
  },

  "holiday-minis": {
    id: "holiday-minis",
    title: "Holiday Mini Sessions",
    description:
      "Festive and magical holiday photography sessions for the whole family.",
    heroImage: "/home/elegant-bride-portrait.png",
    totalPhotos: 3,
    photos: [
      {
        id: "hm1",
        src: "/home/gallery-4.png",
        alt: "Holiday mini session",
        title: "Holiday Magic",
        date: "2024-12-07",
        location: "Marlton, NJ",
        tags: ["holiday", "mini-session", "family"],
        featured: true,
        order: 1,
        uploadedAt: "2024-12-07T11:00:00Z",
      },
      {
        id: "hm2",
        src: "/home/hero (27).jpg",
        alt: "Holiday photography session",
        title: "Festive Moments",
        date: "2024-12-07",
        location: "Marlton, NJ",
        tags: ["holiday", "mini-session"],
        featured: false,
        order: 2,
        uploadedAt: "2024-12-07T11:30:00Z",
      },
      {
        id: "hm3",
        src: "/home/elegant-bride-portrait.png",
        alt: "Holiday portrait session",
        title: "Winter Elegance",
        date: "2024-12-14",
        location: "Cherry Hill, NJ",
        tags: ["holiday", "portrait", "winter"],
        featured: false,
        order: 3,
        uploadedAt: "2024-12-14T10:00:00Z",
      },
    ],
  },
}
